import Media from "../Media";
import { Mode } from "./type";

const movie: Mode = {
    name: "Movie",
    formats: [
        "{n.colon(' - ')} ({y}){' CD'+pi}",
        "{n} ({y}, {director})",
        "{n.space('.')}.{y}{'.'+source}",
        "{ny}/{ny}{' CD'+pi}",
        "{genre}/{n} [{y},{certification},{rating}]",
        "{home}/Movies/{ny.colon(' - ')}",
    ],
    sample: new Media({
        n: "Avengers : L'Ère d'Ultron",
        y: 2015,
        primaryTitle: "Avengers: Age of Ultron",
        alias: "[Avengers: Age of Ultron]",
        id: 99861,
        actors: [
            "Robert Downey Jr.",
            "Chris Evans",
            "Mark Ruffalo",
            "Chris Hemsworth",
            "Scarlett Johansson",
            "Jeremy Renner",
            "James Spader",
            "Samuel L. Jackson",
            "Don Cheadle",
            "Aaron Taylor-Johnson",
            "Elizabeth Olsen",
            "Paul Bettany",
            "Cobie Smulders",
            "Anthony Mackie",
            "Hayley Atwell",
            "Idris Elba",
            "Linda Cardellini",
            "Stellan Skarsgård",
            "Claudia Kim",
            "Thomas Kretschmann",
            "Andy Serkis",
            "Julie Delpy",
            "Stan Lee",
            "Henry Goodman",
            "Chris Luca",
            "Brian Schaeffer",
            "Dominique Provost-Chalkley",
            "Isaac Andrews",
            "Gareth Kieran Jones",
            "Chan Woo Lim",
            "Minhee Yeo",
            "Bentley Kalu",
            "Julian Bleach",
            "Christopher Beasley",
            "Vuyo Dabula",
            "Nondumiso Tembe",
            "Kabelo Thai",
            "Lele Leowaba",
            "Mandla Gaduka",
            "Harriet Manamela",
            "Beulah Hashe",
            "Musca Kumalo",
            "Mathapelo September",
            "Antony Acheampong",
            "Chioma Anyanwu",
            "Ben Sakamoto",
            "Imogen Poynton",
            "Isabella Poynton",
            "Ingvild Deila",
            "Sunny Yeo",
            "Namju Go",
            "Mina Kweon",
            "Earl T. Kim",
            "Arthur Lee",
            "Verity Hewlett",
            "Michael Matovski",
            "Alma Noce",
            "Riccardo Richetta",
            "Constanza Ruff",
            "Monty Mclaren-Clark",
            "Julia Krynke",
            "Tony Christensen",
            "Ian Kay",
            "Barry Aird",
            "Aaron Himelstein",
            "Kerry Condon",
            "Jaiden Stafford",
            "Dilyana Bouklieva",
            "Joti Nagra",
            "Nick W. Nicholson",
            "Daniel Westwood",
            "Josh Brolin",
            "Robert J. Fraser",
        ],
        genre: "Action",
        genres: ["Action", "Aventure", "Science-Fiction"],
        certification: "PG-13",
        rating: 7.3,
        t: "Une nouvelle ère est venue",
        d: "2015-04-22",
        director: "Joss Whedon",
        collection: "Avengers - Saga",
        ci: 2,
        type: "Movie",
    }),
};

export default movie;
